@startuml
left to right direction
actor User
actor Manager

rectangle "Hệ thống Mượn trả sách tự động" {
    (Đăng nhập) as UC1
    (Xác thực tài khoản) as UC2
    (Hiển thị giao diện chính) as UC3
    (Thông báo lỗi) as UC4
}

User --> UC1
Manager --> UC1

UC1 .> UC2 : <<include>>  
UC1 .> UC4 : <<extend>>   
UC2 .> UC3 : <<include>
@enduml
