@startuml
actor "Reader" as reader
participant "Library System" as system
database "Book Database" as db

alt Book Quantity is valid
system -> reader : Display 'Borrow' button
reader -> system : Choose 'Borrow' button
system -> reader : Display Loan-book form (Tên sách, Mã sách, Tên tác giả, NXB, Ngày mượn mặc định)
reader -> system : Điền thông tin ngày trả sách và xác nhận
system -> db : Lưu thông tin mượn sách
db --> system : Xác nhận mượn sách thành công
system -> reader : Hiển thị thông báo "Mượn sách thành công"

else Book Quantity is invalid
system -> reader : Display 'Waitlist' button
reader -> system : Choose 'Waitlist' button
system -> reader : Cung cấp lịch dự kiến sách sẽ có sẵn
reader -> system : Choose 'Wait' or 'Not'
alt Wait
    system -> reader : Display waitlist form (Tên sách, Mã sách, Tên tác giả, NXB, Ngày mượn mặc định)
    reader -> system : Điền thông tin ngày trả sách và xác nhận
    system -> db : Lưu thông tin mượn sách
    db --> system : Xác nhận mượn sách thành công
    system -> reader : Hiển thị thông báo "Bạn đến lấy sách đúng hẹn nhé"
else Not Wait
    system -> reader : Kết thúc quá trình
end
end

@enduml
